### ISSUE TITLE
Run terminal from script?

### ISSUE THREAD

**Issue by nick-ollier** [johnlindquist/kit#1003]
Hello 👋 

I have a command that allows me to open up a project in VS Code.  At the same time I would like to open it up in my preferred terminal, Hyper.

Currently, `term()` only opens the terminal within ScriptKit itself.

Is this achievable?

Thanks 😊

```
// Menu: Open a VSCode Project
// Description: Open a Project in VSCode
import "@johnlindquist/kit";

const projectDirPath = "~/Desktop/Projects";

const projects = ls(projectDirPath).map((dir) => {
  const fullPath = path.join(projectDirPath, dir);
  return {
    name: dir,
    value: fullPath,
    description: fullPath,
  };
});

const project = await arg("Select project:", projects);

edit(project);

// Open preferred terminal here?
await term(...);

```

**Comment by johnlindquist** [comment]
I know you can open Hyper to a specific directory:

```js
// Name: Open Hyper with Directory

import "@johnlindquist/kit"

await $`open -a hyper ~/dev`
```

[Open open-hyper-with-directory in Script Kit](https://scriptkit.com/api/new?name=open-hyper-with-directory&url=https://gist.githubusercontent.com/johnlindquist/45e22b46e1a8c02687f0a82c83e57a84/raw/2b7e9785411b78ccaeb88c6e7744fa66fc20793e/open-hyper-with-directory.ts")

I haven't been able to find a way to open Hyper then run a command though. If you find something, please let me know!

**Comment by nick-ollier** [comment]
> I know you can open Hyper to a specific directory:
> 
> ```js
> // Name: Open Hyper with Directory
> 
> import "@johnlindquist/kit"
> 
> await $`open -a hyper ~/dev`
> ```
> 
> [Open open-hyper-with-directory in Script Kit](https://scriptkit.com/api/new?name=open-hyper-with-directory&url=https://gist.githubusercontent.com/johnlindquist/45e22b46e1a8c02687f0a82c83e57a84/raw/2b7e9785411b78ccaeb88c6e7744fa66fc20793e/open-hyper-with-directory.ts%22)
> 
> I haven't been able to find a way to open Hyper then run a command though. If you find something, please let me know!

Cheers John!  I'll use this as a starting point and will follow up if I figure something out!
