### ISSUE TITLE
[Windows] Unable to install - Unhandled Promise Rejection (clipboard_x86_64.exe)

### ISSUE THREAD

**Issue by William-Owen** [johnlindquist/kit#1007]
Unable to install **Script Kit 1.40.62** on **Windows 11**

```
Unhandled Promise Rejection
Error: spawn C:/Users/William Owen/AppData/Local/Programs/kit/resources/fallbacks/windows/clipboard_x86_64.exe ENOENT
    at r (C:/Users/William Owen/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:543688)
    at n (C:/Users/William Owen/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:543859)
    at ChildProcess.e.emit (C:/Users/William Owen/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

I checked a previous similar error and confirmed my `C:\Users\isman\.knode\bin` folder was correctly named, which it was.

I checked the logs and notices that there were a few references to my user folder that were truncated. Note the references to `Error: C:\Users\William not found` where the user folder is called `C:\Users\William Owen`.

```
[2023-01-19 09:31:38.981] [info] 🔨 Running Setup Script C:\Users\William Owen\.kit\setup\setup.js
[2023-01-19 09:31:39.551] [info] file:///C:/Users/William%20Owen/.kit/core/utils.js:182
    throw new Error(`${script} not found`);
          ^

Error: C:\Users\William not found
    at resolveToScriptPath (file:///C:/Users/William%20Owen/.kit/core/utils.js:182:11)
    at run (file:///C:/Users/William%20Owen/.kit/core/utils.js:446:26)
    at runCli (file:///C:/Users/William%20Owen/.kit/cli/kit.js:134:15)
    at async file:///C:/Users/William%20Owen/.kit/run/terminal.js:16:1

[2023-01-19 09:31:39.552] [info] file:///C:/Users/William%20Owen/.kit/core/utils.js:182
    throw new Error(`${script} not found`);
          ^

Error: C:\Users\William not found
    at resolveToScriptPath (file:///C:/Users/William%20Owen/.kit/core/utils.js:182:11)
    at run (file:///C:/Users/William%20Owen/.kit/core/utils.js:446:26)
    at runCli (file:///C:/Users/William%20Owen/.kit/cli/kit.js:134:15)
    at async file:///C:/Users/William%20Owen/.kit/run/terminal.js:16:1
```

It looks like somewhere a script is being references that is not taking into account the space in the user directory name.

**Comment by tcdvm** [comment]
I'm also experiencing the same problem when trying to install 1.40.62 on Windows 11. Gives the above message (my specific one below) and then the install hangs. 

Unhandled Promise Rejection
Error: spawn C:/Users/tcdvm/AppData/Local/Programs/kit/resources/fallbacks/windows/clipboard_x86_64.exe ENOENT
    at r (C:/Users/tcdvm/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:543688)
    at n (C:/Users/tcdvm/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:543859)
    at ChildProcess.e.emit (C:/Users/tcdvm/AppData/Local/Programs/kit/resources/app.asar/main.prod.js:2:544000)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)Unhandled Promise Rejection

I will note that my username and path does not have spaces so I'm not sure how my error relates to the above's but the error messages are more or less identical except for the home dir in the path. Hope this gets resolved as I installed this on my home PC (also windows 11) and it worked great and I love it!

**Comment by johnlindquist** [comment]
@tcdvm Can you think of any differences between your working machine and this setup? I'm unable to reproduce on my two windows machines at home, so I would love any hint on something to try...

**Comment by johnlindquist** [comment]
@William-Owen I wrote up how to manually install Script Kit when things go wrong here:

https://github.com/johnlindquist/kit/discussions/121#discussioncomment-4752431

It looks like you're getting stuck on this line, can you try running it from the command line and please let me know the results?

```
cd ~/.kit && ~/.knode/bin/node ~/.kit/run/terminal.js ~/.kit/setup/setup.js
```

ChatGPT said that command would look be this for windows:

```
cd %userprofile%\.kit & %userprofile%\.knode\bin\node %userprofile%\.kit\run\terminal.js %userprofile%\.kit\setup\setup.js
```

If that successfully runs, you should be able to open the app.

**Comment by tcdvm** [comment]
@johnlindquist  Ugh tried restarting to see if there were any weird conflicts and getting a different error now:

Unhandled Promise Rejection
Error: write EOF
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)    

Sorry I misspoke on the Windows version. The non-working is Windows 10 Pro while the working is Windows 11. I don't have admin rights on the Windows 10 Pro machine and it has some bloat that makes the install very slow. That's about the only difference, but of course there's a lot of other variable between what's installed on either machine.

I'll try the manual method you referred to above and see how that goes because the errors don't seem to be repeatable. 

Sorry again for the confusion and I'll update this threat with progress (if any). Really do think the app is pretty nifty and the closest thing to something that meets my needs. Hope I get it to work. Thanks for all your hard work.

**Comment by johnlindquist** [comment]
@tcdvm I wonder if it's an admin rights thing. I'll set up a non-admin account on my machine and try to reproduce

**Comment by tcdvm** [comment]
@johnlindquist Thanks John. Perhaps it is an admin problem. I always assumed if it was in the local app directory it'd install fine (like Visual Studio Code or chrome). I did run the ChatGPT suggested install but when running C:\Users\tcdvm\AppData\Local\Programs\kit\Kit.exe it tries to complete the install and fails again with the EOF error. Below is the success message for the ChatpGPT (some minor edits to the node path and I had to add that node path to %PATH% in order for it to find some of the binaries in that directory)

C:\Users\tcdvm>C:\users\tcdvm\.knode\node-v16.17.1-win-x64\node C:\users\tcdvm\.kit\run\terminal.js C:\users\tcdvm\.kit\setup\setup.js

added 1 package, and audited 3 packages in 6s
npm notice
npm notice New major version of npm available! 8.15.0 -> 9.3.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.3.1>
npm notice
found 0 vulnerabilities
 Run `npm install -g npm@9.3.1` to update!
npm notice

Maybe I'll finagle the IT guy into running the install with privileges if it works for you. Thanks again!

**Comment by danielnovta** [comment]
I think 
[util.ts Line645](https://github.com/johnlindquist/kit/blob/f2f27d9ecf71d65de44028771e6f175b73fdfa88/src/core/utils.ts#L645)
this regex does not work properly when the  %userprofile% Path contains a <kbd>space</kbd>.

**Comment by johnlindquist** [comment]
@danielnovta Good find. A space was meant to indicate an "arg" being passed in, e.g., `create-project my-project`

Hmm, let me see if I can get that sorted tonight...

**Comment by johnlindquist** [comment]
@William-Owen @danielnovta I published a pre-release build that should handle spaces:

Please test it out and let me know if the error persists:

https://github.com/johnlindquist/kitapp/releases/tag/v1.40.65

**Comment by danielnovta** [comment]
@johnlindquist 
hi,

I used "Kit-Windows-1.40.65-x64.exe" it worked flawless!

I'm really enjoying Script Kit - thank you and keep up the good work!!

**Comment by William-Owen** [comment]
@johnlindquist - Installed successfully `Kit-Windows-1.40.65-x64.exe`. Thank you.
