### ISSUE TITLE
How do I grant access to the filesystem on MacOS?

### ISSUE THREAD

**Issue by paustint** [johnlindquist/kit#1016]
```
Error: EISDIR: illegal operation on a directory, read
```

How do I grant access to files and folders on Macos?

On a new install, this fails `await ensureFile(home("foo.md"));`

Usually when a program (e.x. terminal) attempts to access a new folder, I get a notification - but I don't see anything show up in kit.

---

Kit 1.40.62
Electron 22.0.0
darwin 21.6.0
Locale: en-US

**Comment by johnlindquist** [comment]
In the system preferences, it should be under "Security and Privacy"

![CleanShot 2023-01-19 at 19 02 22](https://user-images.githubusercontent.com/36073/213602296-7719f226-7486-43da-95e7-25a1ada41611.png)

**Comment by paustint** [comment]
@johnlindquist - I tried to give full access but still get the access denied error message.

Also, I would expect to get a notification from the OS asking me to grant access, but nothing ever popped up.

_(and since I gave full access, it appears there is no way to revoke full access 😨 - the option to select is disabled )_

![image](https://user-images.githubusercontent.com/5461649/213610531-94cf4194-038e-4c0e-abb1-b17072755f7d.png)

**Comment by paustint** [comment]
I revoked access and now it looks like it is working - Kit does not show up in files and folders and is unselected in full disk access... 🤷

**Comment by paustint** [comment]
Hmm.... Actually, it looks like the error happens when playwright times out. That error message seems odd, maybe a log is trying to be saved somewhere without access?

This is the log entry accompanied by the error message:
```
[2023-01-19 18:53:03.235] [warn] ☠️ ERROR PROMPT SHOULD SHOW ☠️
[2023-01-19 18:53:03.236] [warn] page.waitForSelector: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('.search-title') to be visible
============================================================
    at global.scrapeSelector (file:///Users/foo/.kit/lib/browser.js:107:16)
    at async file:///Users/foo/.kenv/scripts/firearm-scraper.js:5:15
[2023-01-19 18:53:03.248] [info] 
$ cd /Users/foo/.kit
```

**Comment by johnlindquist** [comment]
@paustint Are you on Discord? Might be easier to chat through it:

https://discord.gg/3xdhG5fyJM

**Comment by johnlindquist** [comment]
Script Kit does try to write an error file to `~/.kenv/tmp/name-of-your-script/error-the-date.txt`...

Does this script work for you?

```js
// Name: Scrape ESPN


import "@johnlindquist/kit"

let results = await scrapeSelector(`https://games.crossfit.com/leaderboard/games/2021?division=1&sort=0`, ".name")

dev(results)
```

[Open scrape-espn in Script Kit](https://scriptkit.com/api/new?name=scrape-espn&url=https://gist.githubusercontent.com/johnlindquist/c08741dc19826ca702434f0fd55682ee/raw/9b84a3273771e2153355b7d8e3a7f8039e72e45e/scrape-espn.ts")
