### ISSUE TITLE
can't move window automatically when I run script kit on another space.

### ISSUE THREAD

**Issue by youngkyo0504** [johnlindquist/kit#1035]
Thank you so much for developing the script kit! But I'm having some issues... 

when I try to run `kit` on a different space other than my main space, it doesn't appear, but when I go back to my main space, it does.

https://user-images.githubusercontent.com/78121870/213897861-63bfbe42-6c2a-4357-a4cd-48ff080232ba.mov

I'm trying to key down `cmd+;` but it doesn't work.

**Comment by johnlindquist** [comment]
Press cmd+; then cmd+0. That should clear the file at ~/.kit/db/prompt.json which stores the positions of the prompts for each script

**Comment by youngkyo0504** [comment]
> Press cmd+; then cmd+0. That should clear the file at ~/.kit/db/prompt.json which stores the positions of the prompts for each script

thanks..! It works. 

would you tell me that it store position?

**Comment by johnlindquist** [comment]
Each script will store its position in that json file. 

It's nice for when you bind a shortcut to a script and you want the window to appear in the same place each time.

Unfortunately, if your add/disconnect a monitor, the stored x/y coordinates can get confused and need to be reset with cmd+0

**Comment by youngkyo0504** [comment]
Thank you for replying🙇‍♂️
