### ISSUE TITLE
I got a sequence of promise rejection and unhandled errors

### ISSUE THREAD

**Issue by AmodeusR** [johnlindquist/kit#1129]
This is one of them. It happened after I threw the errors after a new script creation, it was my second one.

```
Error: EPERM: operation not permitted, rename 'C:\Users\AmodeusR\.kit\db\.scripts.json.tmp' -> 'C:\Users\AmodeusR\.kit\db\scripts.json'
```

[2023-02-16 15:10:32.224] [info] Verifying ~/.kenv exists:
[2023-02-16 15:10:32.226] [info] kenv found
[2023-02-16 15:10:32.227] [info] node found
[2023-02-16 15:10:32.228] [info] node found
[2023-02-16 15:10:32.230] [info] node_modules found
[2023-02-16 15:10:32.231] [info] node_modules found
[2023-02-16 15:10:32.232] [info] kenv is configured
[2023-02-16 15:10:32.234] [info] kenv .env found
[2023-02-16 15:10:32.235] [info] Install verified

Kit 1.48.0
Electron 22.0.3
win32 10.0.19045
Locale: pt-BR

**Comment by johnlindquist** [comment]
Does it keep happening or did it only happen once?

**Comment by johnlindquist** [comment]
If you manually delete `C:\Users\AmodeusR\.kit\db\scripts.json`, then open the main prompt again, does the error stop?

**Comment by AmodeusR** [comment]
It just stopped after some time... If it occurs again, I'll try deleting it and coming back here to tell it.

**Comment by AmodeusR** [comment]
This error also happened with timestamps. I tried deleting it but the error ocurred again after some time. The errors happens multiple times, not necessarily with the same file name but the directories are the same.

The first time errors happened about 4/5 times. This time around happened about 3 times, and till now not less than 2 times. 

I didn't catch any pattern yet other than it happens when I try to create a new script...
