### ISSUE TITLE
[Bug] Kit cli helper descriptions are undefined 🐛 

### ISSUE THREAD

**Issue by zzeleznick** [johnlindquist/kit#113]
## Background

After updating `~/.kit` to the latest [`1.1.0-beta.86`](https://github.com/johnlindquist/kit/releases/tag/1.1.0-beta.86), I'm seeing `$ kit -h` showing `undefined` for the command descriptions.

<img width="435" alt="kit cli message undefined" src="https://user-images.githubusercontent.com/5779832/113490604-0a08b680-9480-11eb-9f82-074b80937892.png">

I think the rename of `message` to `placeholder` in [`80ea123`](https://github.com/johnlindquist/kit/commit/80ea12329a64b477831c6921122530baf60d5a27) missed a few cases – https://github.com/johnlindquist/kit/blob/80ea12329a64b477831c6921122530baf60d5a27/cli/kit.js#L81 
https://github.com/johnlindquist/kit/blob/80ea12329a64b477831c6921122530baf60d5a27/cli/kit.js#L87
https://github.com/johnlindquist/kit/blob/80ea12329a64b477831c6921122530baf60d5a27/cli/kit.js#L95

## Repro

`$ kit -h`

**Comment by johnlindquist** [comment]
Thanks for the catch!

I was really hesitant to rename "message" to "placeholder". "message" had been the name since the very first experiments. But "placeholder" just made too much sense with the App being the main entry point.
