### ISSUE TITLE
Calculator not working: number-handler.js not found

### ISSUE THREAD

**Issue by daanlenaerts** [johnlindquist/kit#1135]
I have discovered Script Kit yesterday and have been really enjoying it. I couldn't imagine a better way to quickly create, manage and use personal scripts and integrate them into my workflow and OS.
Thank you for building this!

I have been experiencing one issue: when trying to run the built-in calculator I get the following error message:
![image](https://user-images.githubusercontent.com/6502147/220303792-c5edfcbe-d754-4f1d-b48a-56f55a55f929.png)

As I have just pressed the key "2", the error shows `number-handler.js 2 not found`.

Is this a known problem, or is this functionality still work in progress?

**Comment by johnlindquist** [comment]
@daanlenaerts Sorry, it's a known issue. You can try out the latest pre-release if you'd like to use it today:

https://github.com/johnlindquist/kitapp/releases/tag/v1.49.5

**Comment by daanlenaerts** [comment]
@johnlindquist Thank you very much for your swift reply. I have tried it out in the pre-release, and now it does indeed work. Thanks a lot!
