### ISSUE TITLE
[Bug] kit rename (mv) does not rename the bin TARGET_PATH file name

### ISSUE THREAD

**Issue by zzeleznick** [johnlindquist/kit#114]
## Background

When renaming a file with `kit rename` from the cli or the `rename` function from the app, `.kit/cli/rename.js` changes the scripts and bin paths, but does not rename the TARGET_PATH file name in the bin file.

i.e. 
https://github.com/johnlindquist/kit/blob/22df1cb553119d15da215f32bd42842354d24dd5/templates/bin/template#L10

This seems to be minor issue and might make for a good first PR. 

If / when contributions are encouraged, I'd be happy to take a first pass on this.

**Comment by johnlindquist** [comment]
Thanks!

Here's the fix:
https://github.com/johnlindquist/kit/commit/9674a6edc95b1596debc3c60d9c64ad3774600bc

The explanation:
Previously there was a bug where is wasn't removing the old bin, so I thought "I'll just `trash` the bin and `mv` it". I was thinking about how the new bin required a rename inside the script as well.

So switched back to using the `await cli("create-bin", "scripts", newScript)` helper. This is the helper that is used when creating a new script.

Hopefully that makes sense.

I'll definitely start accepting PRs/bugs after release. But I don't want anyone doing work during the beta that I may just end of throwing away.
