### ISSUE TITLE
Typescript scripts are not compiled when using a custom `kenv`

### ISSUE THREAD

**Issue by brpaz** [johnlindquist/kit#1151]
I have created a custom `kenv` to store all my scripts in a GitHub repo.

I noticed that they are not being compiled to `mjs` automatically, unlike if I place them in the main `kenv`.

**Comment by johnlindquist** [comment]
@brpaz Are they running? (it's working on my setup)

If the script is here:

`~/.kenv/my-kenv/scripts/hello-world.ts`

if should compile to that kenvs' .scripts dir

`~/.kenv/my-kenv/.scripts/hello-world.mjs`

**Comment by brpaz** [comment]
Yeah. It worked now. Not sure what happened. Will close this
