### ISSUE TITLE
Notifications in dnd mode don't show up

### ISSUE THREAD

**Issue by phifa** [johnlindquist/kit#1175]
When dnd mode on Mac OS is off, notifications work perfectly. When dnd mode is enabled and the kit app is added to allowed apps in the OS focus settings, the notifications still do not show up. I tested it with this script: 

```
// Name: Stand Up and Stretch
// Schedule: */15 * * * *

import "@johnlindquist/kit"

notify(`Stand up and stretch`)
```

The notifications get collected in the sidebar, but do not appear on screen.

**Comment by johnlindquist** [comment]
I don't understand. Are you expecting notifications to appear while dnd is on? I thought dnd disabled notifications from all apps so if you're sharing your screen, etc, no one can see potentially private info

**Comment by phifa** [comment]
ah that was it! seems to work, thanks John! 🚀
