### ISSUE TITLE
Can't run scripts

### ISSUE THREAD

**Issue by dutzi** [johnlindquist/kit#122]
Hey, I just installed Kit on MacOS 11.2.3 

Not sure what to expect, but pretty certain it's not behaving correctly, see video in link:

https://streamable.com/d1ll9d

**Comment by johnlindquist** [comment]
Please check your:

environment vars:
`~/.kenv/.env`

and logs:
`~/.kenv/logs`

If you don't have an editor set, or you've selected an editor I haven't tested much, there's probably an error logged somewhere. For example, my `.env` is set to use vs code:
`KIT_EDITOR=code`

**Comment by dutzi** [comment]
Oh. I was using the wrong hotkey, I thought Cmd+Shift+; runs the selected script 🙄
