### ISSUE TITLE
Look like some symbols are broken for some reason

### ISSUE THREAD

**Issue by DavidArutiunian** [johnlindquist/kit#1223]
I just installed ScriptKit on my MacBook Pro 16 M1 Pro and I see broken symbols for some reason. Nothing has been changed so far, it's fresh install of an app.

Here how it looks

<img width="414" alt="Screenshot 2023-04-29 at 17 07 49" src="https://user-images.githubusercontent.com/17799810/235307196-35da05b7-16b2-42cf-a91f-f3a85b43e412.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/17799810/235307211-557b7fe4-a67a-448a-a50c-b6bb7bac0db7.png">

Any ideas how to fix this?

**Comment by johnlindquist** [comment]
@DavidArutiunian Hrmm, that uses a bundled "JetBrains Mono" font. Any chance you have JetBrains Mono installed on your system and there's some sort of conflict?

**Comment by DavidArutiunian** [comment]
@johnlindquist yeah, I have JetBrains Mono font installed on my system, but I use it in VSCode 🤔 I could try removing it from system to see if that fixes this bug but I'll still need this font on a machine

**Comment by DavidArutiunian** [comment]
@johnlindquist yeah, that fixed a problem but I think need to be handles in some way so that people with JetBrains Mono won't struggle with that again 🙂

**Comment by johnlindquist** [comment]
@DavidArutiunian Could you tell me the version of your "JetBrains Mono" system font? I don't know if there's a possible version conflict. This seems really strange to me. The CSS just says "font-family: "JetBrains Mono"

**Comment by DavidArutiunian** [comment]
I'm not sure I can find a version, cause I installed it via system font book. I'll try to upgrade JetBrains Mono to a latest version

**Comment by johnlindquist** [comment]
Sorry, I don't know what "Nerd Font version" is

**Comment by DavidArutiunian** [comment]
It's a font with icons for a powerline prompt. It enables icons in terminals
<img width="422" alt="image" src="https://user-images.githubusercontent.com/17799810/235307955-568882ed-7cb6-4220-8a22-989cf14d9b79.png">

**Comment by johnlindquist** [comment]
I'll see if I can do something like "font-family: "JetBrains bundled" or some other trick to force it to use the bundled version

**Comment by DavidArutiunian** [comment]
@johnlindquist yeah, seems that was an issue with outdates JetBrains Mono installed. Issue is gone after I upgraded both `JetBrains Mono` and `JetBrains Mono Nerd Font` versions, thanks! 🙏

**Comment by johnlindquist** [comment]
@DavidArutiunian Cool, thx for letting me know. I'm changing the font loading regardless to avoid something like this happening again.
