### ISSUE TITLE
Not responsive after using for a while

### ISSUE THREAD

**Issue by re4388** [johnlindquist/kit#1265]
I experienced some non-responsive case and I have to force-close it and restart to make it work again.
The frequency is like 1 or 2 per days.

I am just wondering if there's any log or way I can do check to know what's going on?

**Comment by johnlindquist** [comment]
@re4388 Are you on mac/windows/linux?

First, check ~/.kit/logs/kit.log

Aldo, each of your scripts will have their own logs at

~/.kenv/logs

Let me know if you see anything. Always have to discuss more live over in our Discord too:


https://discord.gg/gFCugcfz

**Comment by re4388** [comment]
I am on Mac.
Thanks your suggestions~~
