### ISSUE TITLE
`onEscape` can't work in editor API

### ISSUE THREAD

**Issue by youngkyo0504** [johnlindquist/kit#1268]
https://github.com/johnlindquist/kit/assets/78121870/ec0d2404-3031-4120-a7c3-c6dcb44c8c69

This is my script code.

```ts
const main = async () => {
  const today = makeDateKey(new Date());
  const filePath = await getFilePath(today);
  let content = await ensureReadFile(filePath, createNewTemplate(today));
  const data = {content }
  editor({
      value: content,
      onInput: autoSave(filePath,data),
      onEscape:(e)=>{
        console.log('escape!!!!!')
        submit(data.content)
      },
    });
};
```

when I keydown ESCAPE,  'escape!!!!!' doesn't exist in log.

**Comment by johnlindquist** [comment]
@youngkyo0504 

The `escape` shortcut will default to the "Back to Main Menu" behavior. 
![CleanShot 2023-06-03 at 08 14 10](https://github.com/johnlindquist/kit/assets/36073/e022ccda-88d8-4544-998e-301a969506ef)

So you either need to:

## Clear out the shortcuts
```js
await editor({
  shortcuts: [],
  onEscape: () => {
    submit("test")
  },
})
```

### Override the escape shortcut

```js
let shortcuts = [
  {
    key: "escape",
    onPress: () => {
      submit("test")
    },
    name: "Submit Test",
    bar: "left",
  },
]

await editor({
  shortcuts,
})
```

> Note: It's often preferable to override the shortcut so the user can see the name/action of the shortcut in the bottom bar.

**Comment by youngkyo0504** [comment]
wow...! It works

thank you for answer my issue 👍
