### ISSUE TITLE
`fields` is blocking `setSelectedText`

### ISSUE THREAD

**Issue by Schmedu** [johnlindquist/kit#1275]
Hey @johnlindquist,

I was trying to implement this script here:
```
let text = await getSelectedText();

let buildPreview = ([search, replacement]) => {
    if (!search) return md(text);
    if (!replacement)
        return md(
            `${text
                .replaceAll("\n", "<br>")
                .replaceAll(search, `<ins>${search}</ins>`)}`
        );
    return md(
        `${text
            .replaceAll("\n", "<br>")
            .replaceAll(search, `<ins>${replacement}</ins>`)}`
    );
};

let [search, replacement] = await fields({
    fields: ["Search", "Replacement"],
    preview: buildPreview([]),
    onChange: async (input, state) => {
        let preview = buildPreview(state?.value);
        setPreview(preview);
    },
});

let result = text.replaceAll(search, replacement);

// Output
await setSelectedText(result);
```

But it never finishes the process. There is a loading indicator after I submit the `fields` and that's where it gets stuck. If I add another `arg` afterwards, if works though. Here is a working example:

```
let [search, replacement] = await fields({
    fields: ["Search", "Replacement"],
    preview: buildPreview([]),
    onChange: async (input, state) => {
        let preview = buildPreview(state?.value);
        setPreview(preview);
    },
});
await arg("Dummy arg", ["foo"])
let result = text.replaceAll(search, replacement);
```
I assume there is something in fields that blocks the UI? 🤔

**Comment by Schmedu** [comment]
![CleanShot 2023-06-12 at 11 18 02-2](https://github.com/johnlindquist/kit/assets/8198764/f5417457-7cac-478c-ac6c-6dc1aa5563f3)
Here is a gif

**Comment by johnlindquist** [comment]
Thanks @Schmedu 

It's a flaw in the "hidden prompt" logic.

Before the prompt can hide, it needs to close the preview pane. (If not, you'll see a flash of the previous preview pane when the next prompt opens. This is because prompt renderer "sleeps" when hidden\*).

`setSelectedText` tells the prompt to "hide", but doesn't tell the `preview` to close, so the prompt gets stuck waiting for the preview state to change.

I've got a fix in that I'll release in the build tonight. 👍

The easiest temp fix is to just toss in a call to `div()` which will automatically close the preview:

```js
let result = text.replaceAll(search, replacement)

div() // <-- "hack" to close the preview pane by switch to a new prompt
await setSelectedText(result)
```



> \* "Sleeping renderer" - I wish it were possible to "render while hidden" to avoid this "wait for close" logic, but it's a limitation of the platform that causes some huge headaches when trying to make UIs that instantly open/close. I've run tests with `setBackgroundThrottling`, but unfortunately, they've all resulting in keeping the renderer active when hidden, which results in wasting CPU/GPU. 
>
> The goal is to have as close to 0% CPU/GPU as possible when hidden, with the only exception being the ~0.1% CPU for the script/data/keyboard watchers, which need to stay active for file changes.

**Comment by Schmedu** [comment]
Thanks John! 🙏
