### ISSUE TITLE
Hard to see against white backgrounds

### ISSUE THREAD

**Issue by MinimumViablePerson** [johnlindquist/kit#128]
Due to the app not having any borders or shadows, it is currently hard to spot where it starts and ends when there's a white background. For example:
![image](https://user-images.githubusercontent.com/16916098/114320151-746ac800-9b0c-11eb-8abc-01ce7274306b.png)
![image](https://user-images.githubusercontent.com/16916098/114320190-ba279080-9b0c-11eb-99bc-81b95a8d29fc.png)

**Comment by johnlindquist** [comment]
Thanks. I'm talking with @vojtaholik tomorrow and will discuss borders/etc to help make it pop a bit.

**Comment by johnlindquist** [comment]
![image](https://user-images.githubusercontent.com/36073/115097721-1f063080-9ee9-11eb-8291-4709e2a550dc.jpeg)

Check out the latest build 🙂

**Comment by MinimumViablePerson** [comment]
![image](https://user-images.githubusercontent.com/16916098/115111282-88348500-9f77-11eb-9ff4-c9aca374e230.png)
Much better, good job!
