### ISSUE TITLE
App does not open

### ISSUE THREAD

**Issue by edgarasben** [johnlindquist/kit#129]
Tried opening the app for the first time, but did not work.

macOS Big Sure (11.2.1) MacBookPro 16"

https://user-images.githubusercontent.com/725324/114321188-c239fd00-9b19-11eb-909a-1e3b97891e90.mov

**Comment by johnlindquist** [comment]
<img width="652" alt="Screen Shot 2021-04-11 at 3 42 05 PM" src="https://user-images.githubusercontent.com/36073/114322277-79178800-9adc-11eb-88b7-d5b59afc460d.png">

Thanks so much for including the video. That error most often occurs after Big Sur updates and you haven't run `git` yet to setup dev tools. Please open a terminal, try to run `git`, and you'll see that same "xcrun" error.

This is usually fixed with `xcode-select --install` or `sudo xcode-select --install`

**Comment by edgarasben** [comment]
No worries. Thank you, I will try!

Are those additional steps needed because of the Beta? If that’s a part of a regular setup, it might trip many people.

**Comment by johnlindquist** [comment]
Great question. Script Kit only requires "git" has been set up.

So only people who haven't set up git will need this workaround. I'll work on making this easier and more obvious for the people this impacts.

I may remove the git requirement in the future, but it's not planned

**Comment by edgarasben** [comment]
Hmm, but I do have `git` installed. Do I still need to run `xcode-select --install` or `sudo xcode-select --install`?

**Comment by johnlindquist** [comment]
That same "xcrun" error should occur when you try to "git clone" from your terminal.

Googling the error, which many, many people run into, shows that running that xcode command is the solution.

Script Kit can't set up until "git clone" works on your system.

**Comment by edgarasben** [comment]
I am using git and git clone quite often. Did not run into similar issues.

**Comment by johnlindquist** [comment]
Can you try removing the 2 directories Kit.app clones, then launch the Kit.app again to see if it clones properly now?
1. `rm -rf ~/.kit`
2. `rm -rf ~/.kenv`

Thanks. Sorry this has been such a hassle. I'll have much more robust verification during install once we get out of Beta.

**Comment by edgarasben** [comment]
No problem!

I've tried but these directories do not exist:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/725324/115110695-f465b780-9f7c-11eb-8be8-7a11ed07bfa0.png">

**Comment by johnlindquist** [comment]
My last recommendation is to manually clone/setup the two repos and then launch the app. Instructions are here:

https://github.com/johnlindquist/kit/discussions/89

**Comment by edgarasben** [comment]
Unfortunately still does not work after those steps:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/725324/115123598-1f243000-9fbe-11eb-8262-073f5af5d827.png">

**Comment by johnlindquist** [comment]
Hmm, Kit.app still uses git to verify the tag of ~/.kit matches the Kit.app version.

There must be something going on between the lib I use and your git installation. I'm using:

https://www.npmjs.com/package/simple-git

Have you done any configuration to git? Maybe it's in a different path than the default?

I'm kind of running out of ideas since this appears to be unique to your system.

**Comment by edgarasben** [comment]
Hmm, I don't think I did anything special to git. It's installed using `brew install git` and it's installed at `/usr/local/bin/git`

**Comment by johnlindquist** [comment]
Did you try the `xcode-select install`? It's an extremely common git issue (although I don't know why yours would be working):

https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa

**Comment by edgarasben** [comment]
Ok that actually worked! Thank you!

I simply did not have xcode development software and I assume many users won't either. I also assume this is only needed for beta?

By the way, how do I close the app?

**Comment by johnlindquist** [comment]
git ships on macs by default. The default git requires devtools as you can see by the issue above. So I'm not requiring dev tools, I'm just requiring git and git requires devtools.

It appears the simplegit library is looking for the default git version, whereas you're using the brew version in the terminal. I'll research if there's a way to point simplegit towards homebrew.

help->quit will close the app.

**Comment by edgarasben** [comment]
I've always used a (probably) default git and it never required dev tools. As I understand dev tools are needed to develop native apps. I am mainly working on web apps. So I never had dev tools installed.

**Comment by johnlindquist** [comment]
It's a Big Sur thing

**Comment by johnlindquist** [comment]
I removed the git requirement from recent builds. This should no longer happen 👍
