### ISSUE TITLE
initial setup hang on downloading nodejs

### ISSUE THREAD

**Issue by crazyxhz** [johnlindquist/kit#1290]
<img width="768" alt="image" src="https://github.com/johnlindquist/kit/assets/6551888/322a984f-d352-44be-9ae0-652b7c15e223">
initial setup hang on downloading nodejs but
I can download nodejs using this link directly
<img width="265" alt="image" src="https://github.com/johnlindquist/kit/assets/6551888/2be379bf-1ad5-40b2-8203-3efa40557f86">

btw, i have nodejs in my path, is this download necessary?

**Comment by johnlindquist** [comment]
Hmm, are you running on a VPN or anything that might block it?

There's also this workaround which may help:

https://github.com/johnlindquist/kit/discussions/1052

**Comment by johnlindquist** [comment]
@crazyxhz Give me 15 minutes and I'll try to add proxy support to the install-kit script

**Comment by johnlindquist** [comment]
@crazyxhz Alright, added this logic to grab proxy info from the env vars:

https://github.com/johnlindquist/install-kit/blob/main/download-node.js#L58

Can you try `npx @johnlindquist/install-kit@latest` again?

**Comment by johnlindquist** [comment]
@crazyxhz Can you try the app I published today? It should check for https_proxy env vars and use them during setup
