### ISSUE TITLE
Error "Choices must be an array. Received object"

### ISSUE THREAD

**Issue by Schmedu** [johnlindquist/kit#1292]
Hey @johnlindquist,
I was trying a previously working script of mine where I am doing something in the lines of:
```
import "@johnlindquist/kit"

let input = await arg(
    {
        placeholder: "How many units?",
        strict: false,
    },
    (input) => {
        return {
            name: input,
            preview: input,
            value: input,
        };
    }
);
```
And this now throws the error: `Choices must be an array. Received object`. Did you change this on purpose? 😅

**Comment by johnlindquist** [comment]
@Schmedu Yeah, that wasn't technically "supported" before, even though it worked...

`(input)=> ` should either return:
- array = choices
- string = panel

I've been saving returning an object for some sort of key/value form in case the need arises in the future, but so far it hasn't.

**Comment by Schmedu** [comment]
Ah okay, I think I saw it in one of the discussions or in a kit somewhere, that's probably where I picked it up from. If I come across it I'll let you know. Thanks so far 🙌🏼
