### ISSUE TITLE
Fuzzy find does not work

### ISSUE THREAD

**Issue by pawk3k** [johnlindquist/kit#1316]
Hi @johnlindquist 
Trying to reproduce the tutorial experience but fuzzy find does not work for the exact same code as in the tutorial 
```js
// Name: Open Project

import "@johnlindquist/kit"

let dirs = await readdir(home("dev"))

let selectedDir = await arg(
  "Open Project:",
  dirs.map(dir => ({
    name: dir,
    description: home("dev", dir),
    value: home("dev", dir),
  }))
)

edit(selectedDir)
```
After first letter => no option appear
<img width="854" alt="Screenshot 2023-07-19 at 13 27 34" src="https://github.com/johnlindquist/kit/assets/22987951/dc1dfda1-56ea-446d-b7be-cea514c950fd">

https://www.scriptkit.com/tutorials/automation-workflows-for-web-developers/scriptkit-showcase/list-and-launch-dev-projects

**Comment by johnlindquist** [comment]
@pawk3k Do any of your projects start with the letter "e"? 

I've been tweaking the default "fuzziness" of the search trying to find a balance between performance and how fuzzy it should be. The next build will fuzzy defaults will allow a lot more results.

Please clarify if that's not what you were talking about...

**Comment by pawk3k** [comment]
I think the problem is gone , yea i had some projects starting with `e` or containing `e` but right now when searching with the same command fuzziness is just right , thanks a lot for your work
