### ISSUE TITLE
Shortcode on Windows gets executed without pressing Space

### ISSUE THREAD

**Issue by patrikzudel** [johnlindquist/kit#1362]
I am not sure if I am doing something wrong, but on Windows, my Shortcodes get executed without pressing spacebar. 

**For example:** 
In my code: 
`// Shortcode: n `

_Behaviour:_
I open the main menu (My hotkey is Control + Space), I press "n" and immediately the script runs. 

_Side effect of this is that I can't search anything that starts with the letter 'n'._

**Comment by johnlindquist** [comment]
Thanks, that's a bug. I've been refactoring to add support for "Keywords" (allow you to immediately display the script in the main menu prefixed by the keyword, like Alfred):

![CleanShot 2023-10-22 at 14 29 27](https://github.com/johnlindquist/kit/assets/36073/ef44f6e2-9b69-4d78-96a6-6513507989bf)

Shortcodes got mangled with "commandChars" during the refactor. "commandChars" use a "submit on type" behavior like you're experiencing, usually in a y/n scenario:

![CleanShot 2023-10-22 at 14 32 50](https://github.com/johnlindquist/kit/assets/36073/61cdbe8d-9281-4269-bf6c-8ca411fd527d)

I'll get it sorted out in the next build.

**Comment by johnlindquist** [comment]
@patrikzudel would you mind testing on this build?

https://github.com/johnlindquist/kitapp/releases/tag/v1.98.9

**Comment by patrikzudel** [comment]
Works well now, thank you!
