### ISSUE TITLE
Keyboard layout and shortcuts

### ISSUE THREAD

**Issue by hakubo** [johnlindquist/kit#139]
Hi,

I have a different keyboard layout on my mac (Colemak)
so my ; is in different place and standard shortcut did not work for me `cmd + ;`

but then I tried `cmd + o` (o is in place where ; is in qwerty keyboard)

so the issue seems to be that Script Kit does not take keyboard layout into consideration.

Thanks!

**Comment by Alarid** [comment]
Hi there, @johnlindquist has answered this with a quick fix here: https://github.com/johnlindquist/kit/discussions/130#discussioncomment-600044

I had the same issue, and I solved it by adding this script in ~/.kenv/scripts:
```javascript
// Shortcut: cmd ctrl shift k
await main("index");
```

You can pick whatever you want for the // Shortcut

**Comment by johnlindquist** [comment]
@hakubo I also use colemak :high-five:

I have colemak running in my keyboard firmware, so it detects it fine. Someday I'll get around to detecting keyboard layout changes, but it's not something I can prioritize at the moment.

You can now change the global keyboard shortcut under help:

<img width="416" alt="Screen Shot 2021-04-18 at 10 27 32 AM" src="https://user-images.githubusercontent.com/36073/115152954-b1651c00-a030-11eb-9106-510edbf04903.png">

It will show you exactly which keys it's detecting when you change it:

<img width="417" alt="Screen Shot 2021-04-18 at 10 28 45 AM" src="https://user-images.githubusercontent.com/36073/115152984-dc4f7000-a030-11eb-8e7b-394f59b56df2.png">

**Comment by hakubo** [comment]
Thanks, that's enough for now!

Colemak FTW :)

I'll close for now.

**Comment by albertobissacco** [comment]
@ohnlindquist  i tried to change the global keyboard shortcut under help as you said, but it doesn't detect the keys.
I would like to set "opt cmd space"

(language ENG , keyboard layout ITA)

**Comment by johnlindquist** [comment]
@albertobissacco that's a bug I introduced in the last release. I'll get it sorted a push out a new release tomorrow.

In the meantime, there's a config file here
`~/.kenv/db/kit.json`

You can change the shortcut there and it should automatically pick it up.

```json
{
  "shortcuts": {
    "kit": {
      "main": {
        "index": "opt cmd space"
      }
    }
  }
}
```
