### ISSUE TITLE
doesn't work on ubuntu 22.04LTS

### ISSUE THREAD

**Issue by vagnermaltauro** [johnlindquist/kit#1391]
![image](https://github.com/johnlindquist/kit/assets/81274178/5e02732c-c515-487c-8fcf-b554cb2b3c2d)

I use ubuntu 22.04 latest

the installation was successful, I used the command: `npx @johnlindquist/install-kit@latest`

then I ran the kit command in my terminal.

but the interface didn't open. If I click with both mouse buttons on the icon shown in the image, nothing appears. And also with the command `CTRL + ; `

how do I solve this?

**Comment by HugeLetters** [comment]
Have the same issue. I've installed from both .deb and .appImage releases - installer worked fine(the one where it asks you for feedback while it's setting everything up), then the UI opens but if you close it, it never opens back up. I have the same icon in taskbar and it doesn't do anything. Restart doesn't help either

**Comment by johnlindquist** [comment]
@HugeLetters @vagnermaltauro Can you see if this thread helps?

https://github.com/johnlindquist/kit/issues/1329#issuecomment-1887677929

**Comment by HugeLetters** [comment]
@johnlindquist I've been using X11, not Wayland. 
But I've tried switching to Wayland now, XWayland seems to be installed and working too - same result.
