### ISSUE TITLE
Linux: Very small window height in some scripts.

### ISSUE THREAD

**Issue by brpaz** [johnlindquist/kit#1399]
Hello.
I am testing ScriptKit v2 on my Fedora 39 machine, and it´s generally working fine, but sometimes, the script kit window behaves strangely.

All the content gets hidden (besides the search bar) and I have to increase the window size to view the full content manually.

![Screenshot from 2023-12-15 21-25-27](https://github.com/johnlindquist/kit/assets/184563/795be48f-2add-4ea6-b7ae-11729c4d7285)

It´s not happening every time, but it seems to happen more frequently with some scripts I made, so maybe I am doing something wrong.

I found this in the logs:

```
`21:36:51.160 › Found generate-password in /home/bruno/.kenv/package.json
21:36:51.164 › function: setPromptAlwaysOnTop: true
21:36:51.165 › SET_CHOICES preloaded false 0 choices
21:36:51.166 › Setting uiAtom to arg
21:36:51.167 › SET_CHOICES preloaded false 0 choices
21:36:51.168 › Message match: 0.9981851201364385
21:36:51.226 › 📐 setBounds: resize: MAIN_HEIGHT -> target: 46 max: 480 height: 46, force: true { x: 896, y: 361, width: 768, height: 46 }
21:36:51.584 › 💁‍♂️ : 402992: HEARTBEAT ignored on current UI. 402992 doesn't match 402748
```

It´s setting the height to 46, for some reason.

Edit: I think this is happening when there is no choices available. but then if the choices are updated, it don´t resize to the correct size.

**Comment by brpaz** [comment]
An example script, with no dependencies, where this is happening:

`nst generatePassword : typeof import("generate-password") = await npm("generate-password");

const length = await arg({
    placeholder: "How many characters?",
    validate: (input) => {
        if (isNaN(Number(input))) {
            return "Please enter a number"
        }
        return true
    }
})

const includeSymbols = await arg({
    placeholder: "Include symbols?",
    choices: ["Yes", "No"],
    defaultValue: "Yes",
})

const passwords = generatePassword.generateMultiple(5, {
    length: Number(length),
    numbers: true,
    excludeSimilarCharacters: true,
    symbols: includeSymbols === "Yes",
    strict: true,
})

await arg({
    placeholder: "Select a password to copy",
    choices: passwords,
    onSubmit: async (input, state) => {
        await copy(state?.focused?.value)
        notify("Copied to clipboard")
    },
    actions: [
        {
            name: "Copy to clipboard",
            shortcut: "c",
            visible: true,
            onAction: async (input, state) => {
                await copy(state?.focused?.value)
                notify("Copied to clipboard")
            }
        }
    ]`

**Comment by johnlindquist** [comment]
@brpaz Thanks, for the report. The internal window size detection measurements apparently have a different behavior on Linux than they do on Windows and Mac. I'm investigating a fix. I'll try to either have a fix or a workaround in the next few days.

**Comment by brpaz** [comment]
cool. thank you. Great work on the V2 btw. I love the new features like Actions and Snippets.

**Comment by johnlindquist** [comment]
@brpaz Here's a build which prevents resizing:

https://github.com/johnlindquist/kitapp/releases/tag/v2.0.43

I'm still investigating if I can possible re-enable resizing before I push the build to public channel

**Comment by brpaz** [comment]
@johnlindquist thanks. just tested it and seems fine. I will close this.
