### ISSUE TITLE
The built-in `getScreens` function times out

### ISSUE THREAD

**Issue by michaelmass** [johnlindquist/kit#1532]
When I use the built-in function called `getScreens`, this error message appears:

```
Timeout after 1 seconds waiting for GET_SCREENS_INFO response
```

Do you think it would be possible to make this timeout configurable using parameters?

<img width="796" alt="image" src="https://github.com/user-attachments/assets/87c0a8f0-02ab-4aef-824a-c4e440fc76c9">

**Comment by johnlindquist** [comment]
@michaelmass Yup, can do. As a temp workaround you can use:

```ts
global.getScreens = async () =>
  (
    await global.getDataFromApp(
      Channel.GET_SCREENS_INFO,
      undefined,
      5000 // timeout
    )
  ).displays
```

**Comment by michaelmass** [comment]
Thanks, I really appreciate it. Script Kit is the best productivity tool I am using, and you did an amazing job with it!
