### ISSUE TITLE
Can't restart after deleting .kenv and.kit files

### ISSUE THREAD

**Issue by chaosmonster** [johnlindquist/kit#204]
In the process of resetting the default editor I deleted the `.kenv` and `.kit` folders. Unfortunately afterwards I am no longer able to reinstall or open the script kit gui.

**Comment by chaosmonster** [comment]
Solution is to also go to `~/Library/Application\ Support/` and delete the folder named `Kit`. 

But a good way to reinit the missing folders would be great

**Comment by johnlindquist** [comment]
Good idea. It reinits kit/kenv, but uses the state.json to track version. I'll force a reinit of that dir if kit is missing

**Comment by johnlindquist** [comment]
Kit will now re-run the initialize/verify process which re-creates .kit on launch if .kit is missing. (before it only ran on version mismatch)
