### ISSUE TITLE
Sharing link via gist is failing

### ISSUE THREAD

**Issue by gr2m** [johnlindquist/kit#219]
Version: 1.3.0-beta.9

Publishing a Gist is not working for me. I just did a fresh install, I didn't mess with any config as far as I know. I get the same error when I try to publish via discussion

https://user-images.githubusercontent.com/39992/116749851-67782080-a9b6-11eb-9eaa-3af78e6b6bc8.mp4

**Comment by johnlindquist** [comment]
Thanks for the report (BIG THANKS for the video). I touched on some internals for `arg` which shared internals with `env` and missed this since all my ENV vars are already set 😅

I'll get this sorted tonight and get a new build out.

**Comment by johnlindquist** [comment]
This should be sorted in the latest build

**Comment by gr2m** [comment]
Confirmed 👍🏼
