### ISSUE TITLE
Tutorial: call to `env` does not display `message` in prompt

### ISSUE THREAD

**Issue by tbremer** [johnlindquist/kit#241]
Going through the tutorial, the call to `env` (line 39) did not surface a message within or before displaying the prompt. Only a floating input with no clear indication if something was happening, video attached.

https://user-images.githubusercontent.com/2998575/117172796-c0b6ca00-ad91-11eb-8f0c-f743a4f0b970.mp4

**Comment by johnlindquist** [comment]
Thanks @tbremer . I'll get that sorted today. There have been some minor API changes since I made the tutorial template and I just hadn't updated some of the properties.

**Comment by tbremer** [comment]
Thanks @johnlindquist! Let me know if I can help in any way.
