### ISSUE TITLE
exec(`open ${url}`) fails to pass on all but the first query parameter

### ISSUE THREAD

**Issue by TreTuna** [johnlindquist/kit#244]
I was working with making some scripts for working with https://obsidian.md/ and ran into an issue with the uri structure they use to open and create new notes.

As they do not have a CLI to open new notes, I am working with their uri structure for this objective (https://help.obsidian.md/Advanced+topics/Using+obsidian+URI). I've used this successfully from my terminal and browsers, however, ScriptKit seems to have an issue with multiple query parameters. I'm not sure yet if this is ScriptKit itself or the underlying shelljs `exec` command it's using.

I was using the `exec(open url)` strategy discussed in this post https://github.com/johnlindquist/kit/discussions/142 to try and create a script that makes a new note in Obsidian via their uri structure using this:
```
const noteName = arg("Name your new note");
exec(`open obsidian://new?vault=TreTuna-Digital-Garden&file=Thoughts%2F${noteName}`)
```
However, it seems that `exec("open {uri}")` has an issue with multiple query params and simply ignores all but the first one. I'm not sure if this is something with ScriptKit or with ShellJS and haven't been able to track it down yet. This isn't something specific to the Obsidian url structure either as I tried uris like this:
`exec("open https://www.scriptkit.com/scripts/johnlindquist?first=works&second=ignore")`
and the actual uri that ends up in the browser is:
`https://www.scriptkit.com/scripts/johnlindquist?name=works`

**Comment by johnlindquist** [comment]
`&` has special meaning in bash/zsh (which exec calls out to). So I believe quotes are required so that it's cast as a string:

```js
exec(
  `open "https://www.scriptkit.com/scripts/johnlindquist?first=works&second=ignore"`
)
```

☝️ This worked for me.

**Comment by TreTuna** [comment]
🤦 This makes complete sense and works for me now. Thought it could be something simple that I was just missing.
