### ISSUE TITLE
Error running new script

### ISSUE THREAD

**Issue by danew** [johnlindquist/kit#326]
I'm currently having an issue getting scripts to run. 

I installed the Center App script from the marketplace, but when I try run the script I'm getting a weird environment issue, see below.

It looks like it might be trying to run the script with an older version of node since `endsWith` seems to be undefined, however, I have confirmed Kit is running with Node 16 and my local default version is 14 which both have this feature. 

What I've tried:
 - Removing ~/.kit and ~/.kenv and reinstalling Kit by re-opening it.

Kit.log:
```
[2021-06-23 10:08:30.036] [info]  CONSOLE_WARN Prompt process index.js id: 94285
[2021-06-23 10:08:30.038] [info]  CONSOLE_WARN Prompt process index.js id: 94285
[2021-06-23 10:08:30.896] [info]  ipc message: [
  '/Users/danew/.kit/cli/error-action.js',
  'index.js',
  "Cannot read property 'endsWith' of undefined\n" +
    "TypeError: Cannot read property 'endsWith' of undefined\n" +
    '    at resolveToScriptPath (file:///Users/danew/.kit/utils.js:8:17)\n' +
    '    at global.run (file:///Users/danew/.kit/api/kit.js:158:26)\n' +
    '    at file:///Users/danew/.kit/cli/app-run.js?uuid=268b471f-37b8-4cc4-a3a0-5dc7908aa152:12:11\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)',
  '/Users/danew/.kit/main/index.js',
  '1',
  '1'
]
[2021-06-23 10:08:30.898] [info]  *** /Users/danew/.kit/cli/error-action.js index.js,Cannot read property 'endsWith' of undefined
TypeError: Cannot read property 'endsWith' of undefined
    at resolveToScriptPath (file:///Users/danew/.kit/utils.js:8:17)
    at global.run (file:///Users/danew/.kit/api/kit.js:158:26)
    at file:///Users/danew/.kit/cli/app-run.js?uuid=268b471f-37b8-4cc4-a3a0-5dc7908aa152:12:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5),/Users/danew/.kit/main/index.js,1,1 ***
[2021-06-23 10:08:30.898] [info]  🛑 kill process: /Users/danew/.kit/main/index.js id: 94285
```

**Comment by johnlindquist** [comment]
@danew thanks for reporting.

I'm going to release a new build tonight/tomorrow which may address this (or at least give more detail to hunt down what's happening). I can't quite think of what would cause `resolveToScriptPath` to fail like those logs show.  The `endsWith` seems to mean that it's receiving an `undefined` instead of a string path to the script, but I can't quite think of how that might happen.

Does this occur when trying to run any other scripts?

**Comment by danew** [comment]
I get the same issue with any of the community scripts, the local ones like dad jokes work fine.

I'll have a try in the next few days with the new release and see if the log has anything additional to add to the story.

**Comment by johnlindquist** [comment]
Are the scripts installed with the "Add to Kit.app +" button? (I'm wondering if that might be the culprit)

**Comment by danew** [comment]
They were indeed

**Comment by johnlindquist** [comment]
Closing this for now, assuming it's fixed. Let me know if not.
