### ISSUE TITLE
Cant open kit("chrome")

### ISSUE THREAD

**Issue by theianjones** [johnlindquist/kit#368]
Im getting this error when I run a script that depends on `kit("chrome")`

```
Cannot find module '/Users/ianjones/.kit/lib/chrome.js' imported from /Users/ianjones/.kit/api/kit.js Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/ianjones/.kit/lib/chrome.js' imported from /Users/ianjones/.kit/api/kit.js at new NodeError (node:internal/errors:329:5) at finalizeResolution (node:internal/modules/esm/resolve:323:11) at moduleResolve (node:internal/modules/esm/resolve:758:10) at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:869:11) at Loader.resolve (node:internal/modules/esm/loader:86:40) at Loader.getModuleJob (node:internal/modules/esm/loader:230:28) at Loader.import (node:internal/modules/esm/loader:165:28) at importModuleDynamically (node:internal/modules/esm/translators:116:35) at exports.importModuleDynamicallyCallback (node:internal/process/esm_loader:30:14) at global.attemptImport (file:///Users/ianjones/.kit/api/kit.js:51:45)
```

Im on Kit version 1.3.0-beta.34.

I have a feeling something is wrong with the `.kit` i have but I'm not sure how to resolve the issue.

**Comment by johnlindquist** [comment]
Those "kit libs" haven't existed for a few months now. They're all just global.

**Comment by theianjones** [comment]
Oh, good to know. I missed that update somewhere. Thanks! 

—
Ian Jones

--- original message ---
On July 24, 2021, 2:32 PM EDT ***@***.*** wrote:



Those "kit libs" haven't existed for a few months now. They're all just global.

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
