### ISSUE TITLE
Should we rename this project to scriptkit on github? 

### ISSUE THREAD

**Issue by nadeemkhedr** [johnlindquist/kit#415]
This project already has great traction, but in GitHub search it's not visible.
When searching with `scriptkit` or `kit` its not the first result

Should we rename it to `scriptkit`  so name is unified?

**Comment by johnlindquist** [comment]
For use-cases like github workflows, webhooks, package.json scripts, etc, people will install this repo with 

`npm i @johnlindquist/kit`

So it's appropriately named.

"Script Kit" is the name of the project consisting of:
- scriptkit.com (I'll move/rename it eventually): https://github.com/eggheadio/scriptkit.app
- the Kit.app: https://github.com/johnlindquist/kitapp
- this `kit` core: (this repo)
- kit-bridge: a small project which connects this repo to the app

It's definitely something I need to take care to clarify in README's on project pages. For now, I'm happy if the project is a little difficult to find while I'm working on docs. There are enough users to provide feedback and not too many to overwhelm me with support requests.
