### ISSUE TITLE
Error deleting non-existent script

### ISSUE THREAD

**Issue by canac** [johnlindquist/kit#436]
Steps to reproduce:

1. Open Kit
2. In the "Run script" box, type a string like "foobar" that doesn't match any scripts.
3. Press `Cmd+Delete` on Mac.
4. The error "Cannot find script based on name or command: foobar" displays.

Kit v1.3.0-beta.58 on Mac 11.5.2

**Comment by johnlindquist** [comment]
What is your expected behavior in this scenario?

**Comment by canac** [comment]
My expected behavior would be for it to just clear the "Run script" input, since that's normally what `Cmd+Delete` does. I wasn't trying to delete a script, so I didn't expect to get an error for that. Obviously, up to you to decide how to handle this, it was just surprising behavior for me.

**Comment by johnlindquist** [comment]
Ah, gotcha, I see how that would be surprising. 

If a script is selected, cmd+delete prompts to "delete script". I'll just change the shortcut or maybe remove it completely. (It's something I use a ton due to a bunch of testing scripts, but I imagine I'm the exception)

**Comment by canac** [comment]
Yeah, changing the shortcut would be a good solution.

**Comment by canac** [comment]
Fixed in c71bd853f651642ab61b0bf3215fa300d40cc11f
