### ISSUE TITLE
White bar in prompt with dark mode on

### ISSUE THREAD

**Issue by jsjoeio** [johnlindquist/kit#54]
## Steps to Reproduce

1. System Preferences > General > Appearance 
2. Toggle "Dark"
3. Open Prompt
4. Observe white bar on side

## Expected

Prompt blends in with appearance colors

## Actual

Prompt has white bar on the side
<img width="482" alt="image" src="https://user-images.githubusercontent.com/3806031/111034853-b2bd7c00-83d4-11eb-941e-fc3c34e0cee5.png">

## Demo

https://user-images.githubusercontent.com/3806031/111033867-71c36880-83d0-11eb-8d9b-b7e8af962ff4.mp4

**Comment by johnlindquist** [comment]
This should be fixed in beta 72. @jsjoeio confirmed?

**Comment by jsjoeio** [comment]
Confirmed it's fixed!

<img width="450" alt="image" src="https://user-images.githubusercontent.com/3806031/111346804-d1717c00-863b-11eb-802e-e42c14c42f4e.png">

**Comment by jsjoeio** [comment]
By the way, how'd you fix it?

**Comment by johnlindquist** [comment]
```
*::-webkit-scrollbar {
  display: none !important;
}
```

It was displaying the native scrollbar for some reason. So we brute-forced hid all native scrollbars. Now only the "SimpleBar" component scrollbar should appear.
