### ISSUE TITLE
Selecting editor didn't work on new mac

### ISSUE THREAD

**Issue by kentcdodds** [johnlindquist/kit#602]
<img width="760" alt="Screen Shot 2021-11-19 at 8 43 53 AM" src="https://user-images.githubusercontent.com/1500684/142650603-688d7a61-bc99-4860-8548-a60424ba1609.png">

The "learn more" sent me to https://www.python.org/doc/sunset-python-2/

**Comment by kentcdodds** [comment]
It's working now. 🤷‍♂️

**Comment by johnlindquist** [comment]
The `code` exectuable (shipped by VS Code) uses default `python`. The default `python` on Monterey is 2.7.

So when Kit invokes `code`, it gives a warning about Kit 😢..

I would have to force the user to install Python 3 and write a custom `code` command to get around this. So dumb. Makes me sad, but I'll just have to live with it until they fix their stuff. Luckily, the warning goes away.


Here's the contents of the `code` command shipped with VS Code if you've ever been curious:

```bash
#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

function realpath() { python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0"; }
CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
ELECTRON="$CONTENTS/MacOS/Electron"
CLI="$CONTENTS/Resources/app/out/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --ms-enable-electron-run-as-node "$@"
exit $?
```

**Comment by kentcdodds** [comment]
Looks like there's not much you can do here 🤷‍♂️ Thanks anyway! Kit is *way* faster now with this new macbook. I'll probably use it for *way* more than I used to 😅

**Comment by johnlindquist** [comment]
Just as validation for myself and to save this screenshot, if you run `code` from VS Code's terminal, you get the same warning

![CleanShot 2021-11-19 at 09 59 11](https://user-images.githubusercontent.com/36073/142661970-d1660211-136e-4123-99c0-bc55d8680736.png)
