### ISSUE TITLE
Changing App Shortcut to "command space" doesn't seem to work.

### ISSUE THREAD

**Issue by nicksergeant** [johnlindquist/kit#630]
I can assign `option space` and the app correctly recognizes this:

![CleanShot 2021-12-01 at 21 04 27](https://user-images.githubusercontent.com/27332/144344057-cdaed2af-3456-4690-9197-4c15f4e518b3.gif)

But if I try to use `command space`, the word `space` does not appear in the dialog confirmations, and the keyboard shortcut doesn't bring up the main window:

![CleanShot 2021-12-01 at 21 03 37](https://user-images.githubusercontent.com/27332/144344131-64b2f622-004e-44e4-8ea9-4a3e68b61982.gif)

**Comment by johnlindquist** [comment]
Interesting...

## Workaround

There's a file at:

`/Users/user/.kit/db/shortcuts.json`

Change the contents to:

```json
{
  "shortcuts": {
    "/Users/johnlindquist/.kit/main/index.js": "cmd space"
  }
}
```

This will work fine. It's only the input that can't detect the <kbd>cmd+space</kbd>

## Why Doesn't It Work?

I honestly don't know. Seems like <kbd>cmd+.</kbd> and <kbd>cmd+`</kbd> don't work either. I tried testing it in Chrome and those keys just don't trigger a `keydown` when "command" is held down. 🤷‍♂️

https://codesandbox.io/s/old-night-4yr6o?file=/src/index.js

I can't find anything anywhere on Google, so I'll keep an eye out, but I'm at a loss.

**Comment by nicksergeant** [comment]
@johnlindquist huh, that is strange! I am able to get that KeyboardEvent to log with `cmd-space`:

![image](https://user-images.githubusercontent.com/27332/144531254-53b92697-1b73-4f1d-a9b4-17c22b9c3652.png)

Maybe some other keyboard shortcut/mapping interfering with things on your machine?

That being said, thanks for the workaround! Will use that for now :)

**Comment by johnlindquist** [comment]
Hmm, thanks for the info. I'll have to try on my other laptop now 🤔
