### ISSUE TITLE
Links to "Discuss Post" for Blog Posts Broken

### ISSUE THREAD

**Issue by maxcell** [johnlindquist/kit#659]
Looks like for[ every blog post](https://www.scriptkit.com/blog) that has "Discuss Post", the anchor tag is empty and reloads the page. I was trying to take a gander and figure out where the code was for the site but couldn't find it. I'd be happy to make the contribution for you since you're already gathering each Discussion post in!

Here's a screen recording of the behavior:

![Recording of me clicking "Discuss Post" and it reloading the page](https://user-images.githubusercontent.com/8431042/146658469-14aa256a-b369-457d-89fe-74fc7ab3b086.gif)

**Comment by johnlindquist** [comment]
Thanks @maxcell !

It was a quick fix:

https://github.com/eggheadio/scriptkit.com/commit/87a0bffa545cb44ca1fab4a25984fe9f1baec46c#diff-bb53dd88e82308084e95a32d4714b351b78fd315ffeb036eb4cd0ca1acbb7175R12

The site is mostly a huge experiment in:
1. Using Script Kit scripts during the build process
2. Using Script Kit scripts in the serverless fns
3. Building an entire site backed by the GitHub discussions API

I would _not_ recommend following any of that code as "best practice" or even "good" 🤣, but it's been a good playground to test out how we can mature Script Kit scripts into other areas 🥂
