### ISSUE TITLE
Can't open Kit after installing from dmg

### ISSUE THREAD

**Issue by doingandlearning** [johnlindquist/kit#69]
What I did:
- Downloaded the dmg
- Dragged to Applications
- Opened application

What I expected:
- To be able to use Kit 

What actually happened:
- I get a flash of an error screen `Kit failed to Install` and then it exits. There is a lot of other info but it crashes before I can grab it.

Running MacOS 11.3

**Comment by doingandlearning** [comment]
Ah - I've solved it - I noticed the error had to do with xcrun and that when my laptop updated last it ditched XCode CLI tools.

I guess most people have this installed already but might be good to error gracefully and/or add to README? :)

**Comment by johnlindquist** [comment]
Thanks for reporting this.

Kit runs a git clone during install to set up the dev environment, so
running git on an updated mac is what triggers the xcrun/xtools prompt. I'm
really not looking forward to reproducing this, lol
