### ISSUE TITLE
Download links in main page yields 404 on click

### ISSUE THREAD

**Issue by kenjox** [johnlindquist/kit#741]
![Screenshot 2022-02-25 at 08 26 59](https://user-images.githubusercontent.com/1942077/155673048-1f93c5cc-2dce-45a3-94e3-1f2a4d52aff5.png)

**Comment by Alarid** [comment]
+1 ! In the meantime, [you can find the download files here](https://github.com/johnlindquist/kitapp/releases/tag/v1.6.9)

**Comment by johnlindquist** [comment]
Thanks for reporting this!

This is _really_ strange. When that page generates, it grabs the URLs to the latest release. But something, somewhere changed on GitHub releases API that hides the latest release when pinged signed-in as show in the screenshot (The API gives the same results)

I'll work around this until I can figure out a "good" solution

![CleanShot 2022-02-25 at 06 17 55](https://user-images.githubusercontent.com/36073/155721837-80f0803b-1eee-4030-8c17-131e6336594d.png)

**Comment by johnlindquist** [comment]
The links are fixed, but I'm leaving this open until I figure out what happened with the API
