### ISSUE TITLE
1.7.0 was broken on my Mac

### ISSUE THREAD

**Issue by xxleyi** [johnlindquist/kit#744]
After update to 1.7.0:

![image](https://user-images.githubusercontent.com/12626454/155839356-5c4dd3f4-4d57-42f2-a6ec-bd6b34791a5f.png)

---

Process:               Kit [98015]
Path:                  /Applications/Kit.app/Contents/MacOS/Kit
Identifier:            Kit
Version:               1.7.0 (1.7.0)
Code Type:             X86-64 (Native)
Parent Process:        Kit [98008]
Responsible:           Kit [98008]
User ID:               502

Date/Time:             2022-02-26 18:12:22.199 +0800
OS Version:            Mac OS X 10.15.7 (19H15)
Report Version:        12
Bridge OS Version:     4.6 (17P6610)
Anonymous UUID:        BE5A80AC-3BF4-4B73-85BF-35700AA45BE4

Sleep/Wake UUID:       EEFEBB68-E488-4F10-918A-2835F4B048A7

Time Awake Since Boot: 660000 seconds
Time Since Wake:       130 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [98015]

VM Regions Near 0x20:
--> 
    __TEXT                 000000010b159000-000000010b15b000 [    8K] r-x/r-x SM=COW  /Applications/Kit.app/Contents/MacOS/Kit

Application Specific Information:
crashed on child side of fork pre-exec

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_malloc.dylib        	0x00007fff6fb34e41 nanov2_forked_calloc + 7
1   libsystem_malloc.dylib        	0x00007fff6fb1ff59 malloc_zone_calloc + 99
2   libsystem_malloc.dylib        	0x00007fff6fb1fed9 calloc + 24
3   libobjc.A.dylib               	0x00007fff6e7b4603 allocateBuckets(unsigned int) + 29
4   libobjc.A.dylib               	0x00007fff6e7b4096 cache_fill + 283
5   libobjc.A.dylib               	0x00007fff6e7b3b27 lookUpImpOrForward + 530
6   libobjc.A.dylib               	0x00007fff6e7b3399 _objc_msgSend_uncached + 73
7   libxpc.dylib                  	0x00007fff6fbbe89e xpc_atfork_child + 125
8   libSystem.B.dylib             	0x00007fff6c94dab8 libSystem_atfork_child + 59
9   libsystem_c.dylib             	0x00007fff6f9c78ad fork + 40
10  com.github.Electron.framework 	0x000000010b1751ef uv_spawn + 527
11  com.github.Electron.framework 	0x0000000111907301 node::PromiseRejectCallback(v8::PromiseRejectMessage) + 234001
12  com.github.Electron.framework 	0x000000010c1b54fb v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) + 12651
13  ???                           	0x0000002807f0aa38 0 + 171931904568
14  ???                           	0x0000002807e8c862 0 + 171931388002
15  ???                           	0x0000002807e8c862 0 + 171931388002
16  ???                           	0x0000002807e8c862 0 + 171931388002
17  ???                           	0x0000002807e8c862 0 + 171931388002
18  ???                           	0x0000002807f5ab62 0 + 171932232546
19  ???                           	0x0000002807e89dcf 0 + 171931377103
20  ???                           	0x0000002807fab9b6 0 + 171932563894
21  ???                           	0x0000002807e8c862 0 + 171931388002
22  ???                           	0x0000002807e8c862 0 + 171931388002
23  ???                           	0x00000028000a7a34 0 + 171799378484
24  ???                           	0x00000028000a8bc8 0 + 171799382984
25  ???                           	0x000000280009d8d6 0 + 171799337174
26  ???                           	0x00000028000a9f8c 0 + 171799388044
27  ???                           	0x000000280009fece 0 + 171799346894
28  ???                           	0x0000002807f5c6f8 0 + 171932239608
29  ???                           	0x0000002807eb3f1e 0 + 171931549470
30  ???                           	0x0000002807e8a7c7 0 + 171931379655
31  com.github.Electron.framework 	0x000000010c286984 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 6260
32  com.github.Electron.framework 	0x000000010c2872c3 v8::internal::Execution::TryCallScript(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::FixedArray>, v8::internal::Execution::MessageHandling, v8::internal::MaybeHandle<v8::internal::Object>*, bool) + 355
33  com.github.Electron.framework 	0x000000010c287430 v8::internal::Execution::TryCall(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*, v8::internal::Execution::MessageHandling, v8::internal::MaybeHandle<v8::internal::Object>*, bool) + 224
34  com.github.Electron.framework 	0x000000010c2b04dc v8::internal::MicrotaskQueue::PerformCheckpointInternal(v8::Isolate*) + 460
35  com.github.Electron.framework 	0x00000001117a2f08 node::CallbackScope::~CallbackScope() + 1256
36  com.github.Electron.framework 	0x00000001117a2a7e node::CallbackScope::~CallbackScope() + 94

  
......

    0x7fff6fb66000 -     0x7fff6fb70fff  libsystem_pthread.dylib (416.100.3) <62CB1A98-0B8F-31E7-A02B-A1139927F61D> /usr/lib/system/libsystem_pthread.dylib
    0x7fff6fb71000 -     0x7fff6fb75ff3  libsystem_sandbox.dylib (1217.141.2) <051C4018-4345-3034-AC98-6DE42FB8273B> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff6fb76000 -     0x7fff6fb78fff  libsystem_secinit.dylib (62.100.2) <F80872AA-E1FD-3D7E-8729-467656EC6561> /usr/lib/system/libsystem_secinit.dylib
    0x7fff6fb79000 -     0x7fff6fb80ffb  libsystem_symptoms.dylib (1238.120.1) <5820A2AF-CE72-3AB3-ABCC-273A3419FB55> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff6fb81000 -     0x7fff6fb97ff2  libsystem_trace.dylib (1147.120) <04B47629-847B-3D74-8ABE-C05EF9DEEFE4> /usr/lib/system/libsystem_trace.dylib
    0x7fff6fb99000 -     0x7fff6fb9eff7  libunwind.dylib (35.4) <42B7B509-BAFE-365B-893A-72414C92F5BF> /usr/lib/system/libunwind.dylib
    0x7fff6fb9f000 -     0x7fff6fbd4ffe  libxpc.dylib (1738.140.1) <3E243A41-030F-38E3-9FD2-7B38C66C35B1> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 97622099
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=825.5M resident=0K(0%) swapped_out_or_unallocated=825.5M(100%)
Writable regions: Total=1.1G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.1G(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               256K        2 
CG image                          12.6M        3 
CoreAnimation                       44K        5 
CoreGraphics                         8K        1 
CoreUI image data                  472K        4 
Foundation                          28K        2 
Kernel Alloc Once                    8K        1 
MALLOC                           196.7M       36 
MALLOC guard page                   48K       10 
MALLOC_MEDIUM (reserved)         240.0M        2         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
Mach message                        24K        4 
Memory Tag 253                    32.0G      746 
STACK GUARD                       56.0M        1 
Stack                            222.4M       41 
Stack Guard                        160K       40 
VM_ALLOCATE                       16.3M      148 
__DATA                            55.6M      439 
__DATA_CONST                        20K        1 
__FONT_DATA                          4K        1 
__LINKEDIT                       393.1M       10 
__OBJC_RO                         32.3M        1 
__OBJC_RW                         1908K        2 
__TEXT                           432.4M      431 
__UNICODE                          564K        1 
mapped file                       64.7M       26 
shared memory                      104K       14 
===========                     =======  ======= 
TOTAL                             34.0G     1973 
TOTAL, minus reserved VM space    33.4G     1973 

Model: MacBookPro16,1, BootROM 1037.147.4.0.0 (iBridge: 17.16.16610.0.0,0), 6 processors, 6-Core Intel Core i7, 2.6 GHz, 32 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro5300MItem, AMD Radeon Pro 5300M, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 16 GB, DDR4, 2667 MHz, Micron, -
Memory Module: BANK 2/ChannelB-DIMM0, 16 GB, DDR4, 2667 MHz, Micron, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Apr  7 2020 13:09:12 version 9.30.357.41.32.5.49 FWID 01-617711e7
Bluetooth: Version 7.0.6f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: Apple T2 Bus
USB Device: Composite Device
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 55.3
Thunderbolt Bus: MacBook Pro, Apple Inc., 55.3

**Comment by johnlindquist** [comment]
Thanks for reporting this. Build 1.7.0 had an issue on the build server, I pulled it as quick as I could, but it looks like your updater caught it before I could take it down.

1.7.3 should be fixed.

If yours doesn't fix itself with an auto-update, then you can download the latest from the main site and overwrite the old version:

https://www.scriptkit.com/
