### ISSUE TITLE
[feat]: no namespace, global pollution with types (typescript)

### ISSUE THREAD

**Issue by alexn-s** [johnlindquist/kit#958]
First of all i really got to say that i love kit. it is amazing (previously used espanso, autohotkey, ...)

It would be great if one could use
```
// Name: sample

import "@johnlindquist/kit"

import * as api from "@johnlindquist/kit"
api.
```

the `import * as api from` as or `import api from`  code.
Just importing kit pollutes intellisense and it is really hard to find something relevant to kit with all the other suggestions

when i am using
```
import * as api from "@johnlindquist/kit"
api.
```
api namespaces does not provide any intelisense and a default export is not available.

**Comment by johnlindquist** [comment]
First off, thank you so much for the sponsorship! 🙏

One approach we could try would look like this:

![CleanShot 2022-12-01 at 17 49 17](https://user-images.githubusercontent.com/36073/205189752-501e48e5-7115-4f47-b65d-fe1bb178cd48.png)

Then you could use `api` to show off selections:

<img width="624" alt="CleanShot 2022-12-01 at 17 50 00@2x" src="https://user-images.githubusercontent.com/36073/205189832-dc2e291f-2f8a-4a66-88e6-077b1f1209e3.png">

It feels like a decent solution to me. Thoughts?

--- 
> Note: The globals are injected into the scripts even if we don't use `import "@johnlindquist/kit"`. The only reason the import exists is for tooling/Intellisense.

**Comment by alexn-s** [comment]
your welcome for sponsoring. definetly worth it and i am excited what the future brings.

---

i personally am not a fan of globals.
is there a reason why you use globals and not a default export.

i guess i was "looking" for a `import api from "@johnlindquist/kit"` syntax, because it felt out of "sync" with other ts code.

i hope you know what i mean 💖

besides that it would be better than before.

**Comment by alexn-s** [comment]
by the way: is there a possibility to navigate the categories by keyboard?

![image](https://user-images.githubusercontent.com/60710873/205200731-a5a1f553-b3f0-4224-916e-29b596dd014f.png)

**Comment by johnlindquist** [comment]
## Why Globals

The choice to use global methods comes from general scripting in bash where you expect all the methods to be available and you just type commands/code directly in the terminal.

I understand most TS devs are coming from a project/front-end mindset when writing code is many files interacting with each other. But a script is a standalone file where globals don't "pollute" into other files and it's more convenient to just quickly type up few lines and "get it done".

Also, with globals, If you launch the debugger, you'll have an interactive playground/REPL where you can simply type methods and hit enter. We can build on top of that concept in the future and launch a fully terminal-like experience.

## Keyboard Nav for Categories

Use "tab" and "shift+tab" to switch between the tabs. You can also type the first character of the tab (for example, "g" for guide) then hit "tab" to just to that specific tab.

## Changelog

The changelog/release notes are generally done as announcements here: https://github.com/johnlindquist/kit/discussions/categories/announcements?discussions_q=category%3AAnnouncements+sort%3Adate_created

I have a lot of work to do for docs/mailing list/etc around communication.

**Comment by alexn-s** [comment]
awesome. thanks for the information and the answers. never thought about the use case of REPL and so.
should i keep this issue open until api in globals is released or do you want me to close this issue?

**Comment by johnlindquist** [comment]
We can close this. I'm going to expose the api two ways:

1. A `kit` global

```js
let name = await kit.arg("Enter your name")
```

2. The default export

```js
import api from "@johnlindquist/kit"

let name = await api.arg("Enter your name")
```

**Comment by alexn-s** [comment]
thats a perfect solution. everyone can use it in their own way. thanks
