### ISSUE TITLE
[issue]: return focus to window when closed

### ISSUE THREAD

**Issue by alexn-s** [johnlindquist/kit#959]
it would be nice if kit would return the focus to the active window before kit was opened.
currently you need to click/ alt+tab in the window or use `kit.keyboard.pressKey(alt+tab)`.

i think a setting value would be neat: `foucsPriorWindowAfterClose: true`

os: windows 11

**Comment by johnlindquist** [comment]
Hmm, that should be the default behavior... It "works on my machine" 😅. I'll run some more tests and try to reproduce.

For now, try adding:

```js
await blur()
```

to the end of your script and see if that helps.

**Comment by alexn-s** [comment]
hmm here is the result from neofetch:

### specs

```
C:\Users\aschu>neofetch
        ,.=:!!t3Z3z.,                  aschu@thehuawei
       :tt:::tt333EE3                  ---------------
       Et:::ztt33EEEL @Ee.,      ..,   OS: Windows 11 Home x86_64
      ;tt:::tt333EE7 ;EEEEEEttttt33#   Host: HUAWEI HVY-WXX9
     :Et:::zt333EEQ. $EEEEEttttt33QL   Kernel: 10.0.22000
     it::::tt333EEF @EEEEEEttttt33F    Uptime: 14 hours, 9 mins
    ;3=*^```"*4EEV :EEEEEEttttt33@.    Packages: 9 (scoop)
    ,.=::::!t=., ` @EEEEEEtttz33QF     Shell: bash 5.1.16
   ;::::::::zt33)   "4EEEtttji3P*      Resolution: 1920x1080
  :t::::::::tt33.:Z3z..  `` ,..g.      DE: Aero
  i::::::::zt33F AEEEtttt::::ztF       WM: Explorer
 ;:::::::::t33V ;EEEttttt::::t3        WM Theme: Custom
 E::::::::zt33L @EEEtttt::::z3F        CPU: AMD Ryzen 5 4600H with Radeon Graphics (12) @ 3.000GHz
{3=*^```"*4E3) ;EEEtttt:::::tZ`        GPU: Caption
             ` :EEEEtttt::::z7         GPU: AMD Radeon(TM) Graphics
                 "VEzjt:;;z>*`         GPU
                                       Memory: 9070MiB / 15741MiB
```


current kit version
C:/Users/.../.kit/package.json
```
 "name": "@johnlindquist/kit",
  "version": "0.34.17",
...
```

---

### question
is it correct that blur is not async?
![image](https://user-images.githubusercontent.com/60710873/205198162-ca353395-b6e1-49fc-9a0f-10ddd40413b8.png)

---

### works for me

```
// Name: sample

import "@johnlindquist/kit"

await keyboard.pressKey(Key.LeftAlt, Key.Tab)
await keyboard.releaseKey(Key.LeftAlt, Key.Tab)

await keyboard.type("hello")

```

### does not work

```
// Name: sample

import "@johnlindquist/kit"

await keyboard.type("hello")
```

```
await blur()
await keyboard.type("hello")
```

```
await keyboard.type("hello")
await blur()
```

**Comment by johnlindquist** [comment]
> is it correct that blur is not async?

I believe that's a bug in VS Code pulling in the types for `lib.dom.d.ts` even though it's a node project (so it thinks it's `window.blur`. I've tried excluding it in my tsconfig before, but I've never had any luck.

**Comment by alexn-s** [comment]
@johnlindquist great work. just donated something next to sponsorship. thank you.

really helpful is that setSelectedText works, and focus work as well. keyboard.type does not work anymore (#972)
