### ISSUE TITLE
[issue]: dynamic choice.value (async) | cannot select choice with enter & wont execute

### ISSUE THREAD

**Issue by alexn-s** [johnlindquist/kit#961]
it appears that a choice with a value of `type async () => string` cannot be selected with enter
and that the function from value wont execute. is it wrong to use a dynamic value?

related: #612 

```
// Name: business-urls

import "@johnlindquist/kit"
import { Choice } from "@johnlindquist/kit"

const choices: Choice[] = [
	{
		name: "amz.de",
		value: async () => {

			const input = await arg("input")
			return `https://www.amazon.de/s?k=${input}`

		}
	}
]


let func = await arg("Select a name", [
	...choices
])

const copyMe = await func()
await copy(copyMe)


```

**Comment by johnlindquist** [comment]
Functions aren't valid values. The value needs to be passed as JSON between the Kit.app and the process running the script so they need to be primitives or serializable JS objects.

If you can come up with a really strong case for "values as functions", I'm open to discussing it and finding a workaround. Otherwise, I'm certain we can find a good solution if you have a specific scenario in mind.

**Comment by alexn-s** [comment]
thanks. my mind came from cli (inquirer, prompt, ...) where if often use functions as values.

in this case i just want to copy/ or type a text snippet with a few inputs.
eg. 
- google url with one input (query)
- wikipedia url with 2 inputs (top level domain & query)

should i use
```ts
		onSubmit: async () => {

			const input = await arg("input")
			const str =  `https://www.amazon.de/s?k=${input}`
                        await copy(str)
}
```
or should i just create a custom type (plain object) and use that as a value to use it and pass it in a custom function

eg
```ts
...
value: {
url: "...",
questions: [...]
}
...


const value = await arg(...)
execQuestion(value) // like this
```
there probably is not a good use case for values as functions if one can use this

**Comment by alexn-s** [comment]
thanks for your help
