### ISSUE TITLE
[issue]: keyboard.type broken on v1.39.16 - windows

### ISSUE THREAD

**Issue by alexn-s** [johnlindquist/kit#972]
while setSelectedText now works
```
await kit.setSelectedText(text)
```

keyboard.type does not work anymore
```
await kit.keyboard.type(text)
```

in the prior version keyboard.type worked and setSelectedText did not.
i dont think this issue is important and can be postponed because setSelectedText is faster and should be sufficient for windows users in most cases.

cleaned the log before running for you
[kit.log](https://github.com/johnlindquist/kit/files/10183119/kit.log)

**Comment by johnlindquist** [comment]
Hmm, this script works on my Windows machine:


```
await hide()
await keyboard.type(`Hello world`)
```

Can you show me your script?

**Comment by alexn-s** [comment]
```ts
// Name: repro

import kit from "@johnlindquist/kit"
import { Choice } from "@johnlindquist/kit"

const runIt = async (text: string) => {
	await kit.keyboard.type(text)
}


const details: Choice[] = [
	{
		name: 'sample',
		onSubmit: () => runIt('sample@gmail.com'),
	},


].map(x => { x.name = `gmail | ${x.name}`; return x })



const choices: Choice[] = [
	...details,
]


let func = await arg("Select something", choices)

```

as an example this does not work for me

**Comment by alexn-s** [comment]
or more simplified

```ts
import kit from "@johnlindquist/kit"

await kit.keyboard.type("hello there")
```

which does not work as well

**Comment by alexn-s** [comment]
but your await hide() appears to do the trick. now it works.

previously it worked without. is it required to use? if so the issue can be closed and could be "labeled" a minor breaking change

**Comment by johnlindquist** [comment]
Yes, "hide" should be required. It was broken before.

It's possible in the future for Kit to have multiple windows and type into its own UI, so sometimes you wouldn't want to "hide" it. 

It's possible "setSelectedText" will require "hide" in the future, but currently it calls hide internally.

**Comment by alexn-s** [comment]
ok thanks for the answer. i am closing the issue
